name: Update flakes
on:
  workflow_dispatch:
  schedule:
    - cron: "10 4 * * 1"

jobs:
  lockfile:
    name: Update Nix lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update Nix flakes
        run: nix flake update
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: flake.lock
          branch: nix/flake-lock-update
          labels: dependencies
          commit-message: "flake.lock automated update"
          title: "Flake update"
          body: ""